const baseMixins = {
  methods: {
    // item为单个任务对象，isAxis判断是否是时间轴页面
    // 跳转到指定页面 obj为指定页面的url对象，键是 taskId 值为需跳转的页面
    routerChange(item, isAxis) {
      const obj = {
        falvyuanzhuyuyue: '',
        falvyuanzhuyuyuexiangying: '',
        shifalvyuanzhuyuyuexiangying: '',
        renmintiaojieyuyueshengqing: '',
        tiaoweihuixiangying: '',
        zhipaitiaoweihui: '',
        zdxzx_lvshixiangying: '',
        mfzx_lvshixiangying: '',
        gw_fw_gwqc: '/ngongwen_qicao',
        gw_fw_bgsyj: '/gongwenyijian',
        gw_fw_fgldyj: '/fenguanlingdaoshenpi',
        gw_fw_ldqf: '/lingdaoqianfa',
        gw_fw_ldhq: '/gongwenfenfa',
        gw_fw_gwff: '/gongwenfenfa',
        gw_fw_fwcy: '/gongwenchuanyue',
        gw_fw_kzsh: '/juzhangqianpi',
        gw_fw_gwxg: '/wenshugengxin',
        gw_rw_rwfb: '/chuanyuewancheng',
        gw_rw_rwfk: '/renwufankui',
        gw_rw_rwjc: '/renwujiancha',
        gw_sw_swdj: '/nshouwen_dj',
        gw_sw_nbyj: '/nibanyijian',
        gw_sw_zrsh: '/zhurenshenhe',
        gw_sw_gwyp: '/gongwenchuanyue',
        gw_sw_ldqp: '/lingdaoqianfa',
        gw_sw_gwff: '/gongwenfenfa',
        gw_sw_gwcy: '/gongwenchuanyue',
        hysq: '/n_meetingApply',
        fgldsp: '/meeting-fenguanlingdao',
        jzsp: '',
        bgsph: '/meeting-bangongshipaihui',
        hyks: '/meeting-qidong',
        hyjs: '/meeting-qidong',
        hyjl: '/meeting-huiyijilu',
        hybz: '/meeting-huiyibuzhi',
        hyqd: '/meeting-qidong',
        hych: '/meeting-canhuihuizhi',
        hygrqd: '/meeting-qiandao',
        chhz: '/meeting-canhuihuizhi',
        hyqj: '/meeting-canhuihuizhi',
        hyqjsp: '/meeting-huiyiqingjiashenpi',
        dept_person_chhz: '/meeting-canhuihuizhi',
        dept_hyqj: '',
        dpet_hyqjsp: '',
        dept_person_hyqj: '',
        dept_person_hyqjsp: '',
        hyqj: '',
        hyqjsp: '',
        hyzp: '',
        gc_qcsq: '/ngongchu_shenqing',
        qc_ksfzrgcsh: '/gongchushenhe',
        gc_fgbmldsp: '/gongchushenhe',
        gc_jzsp: '/gongchushenhe',
        gc_flow_hb: '/gongchuhuibao',
        gc_ksfzrhbsh: '/gongchuhuibaoshenhe',
        gc_fgldhbsp: '/gongchuhuibaoshenhe',
        gc_jzhbsp: '/gongchuhuibaoshenhe',
        gc_flow_hbtz: '',
        qj_qjsq: '/n_qingjia',
        qj_ksfzrsp: '/qingjiashenpi',
        qj_fgbmldsp: '/qingjiashenpi',
        qj_jzsp: '/qingjiashenpi',
        yc_flow_ycsq: '',
        yc_flow_ycsp: '',
        chuangjianzhanghao: '',
        lvshishenbao: '',
        fuzerenshenhe: '',
        keyuanshenhe: '',
        kezhangshenhe: '',
        'sid-248BC82F-EADB-4BDC-964F-A8CA5A0330E7': '',
        'sid-BBD468F4-5AB3-47D4-BD0B-077AACBA7461': '/wanshan',
        zcsq_tjsq: '/n_assetsRecipients',
        zcsq_kzsh: '/zichan-lingdaoshenhe',
        zcsq_fgjzsh: '/zichan-lingdaoshenhe',
        zcsq_fgcwfjzsh: '/zichan-lingdaoshenhe',
        zcsq_zcck: '/chukudengji',
        zcsq_jzsh: '/zichan-lingdaoshenhe',
        zcsq_zclq: '/zichanlingqu',
        zcsq_wtlq: '/weituolingqu',
        zcsq_zcrk: '/zichanruku',
        zcsq_zcgh: '/zichanguihai',
        zcsq_wtgh: '/weituoguihai',
        sfj_px_kjxx: '',
        ycsq_ycsq: '/nyongcheshenqing',
        ycsq_kssh: '/keshishenhe',
        ycsq_fgldsh: '/keshishenhe',
        ycsq_zgbmldsh: '/keshishenhe',
        ycsq_ccdj: '/chuchedengji',
        ycsq_hcdj: '/haichedengji',
        ycsq_clrk: '/cheliangruku',
        vehicle_apply_cancel_approve: '/keshishenhe',
      };
      // 结构赋值
      const {instanceId, taskId, businessId, taskDefKey, taskKey} = item;
      // 跳转指定页面 兼容处理，有页面才跳
      const path = isAxis ? obj[taskKey] : obj[taskDefKey];
      if (path) this.$router.push({path, query: {instanceId, taskId, businessId, taskDefKey}})
    }
  }
};
export default baseMixins
