//公共
export const COM_LOADING = 'COM_LOADING';
export const COM_LOGIN = 'COM_LOGIN';

// 登录
export const LOG_GETUSERINFO = 'LOG_GETUSERINFO';
export const LOG_GETSYSPARAMS = 'LOG_GETSYSPARAMS';
export const INDEX_GETMENULIST = 'INDEX_GETMENULIST';

//首页
export const INDEX_COLLAPSE = 'INDEX_COLLAPSE';